#!/usr/bin/env python3
"""Apply safe deterministic repairs to the published Job Alerts HTML.

This script intentionally avoids search/scoring policy changes. It only removes or
normalizes defects that validation can identify mechanically.
"""

from __future__ import annotations

import datetime as dt
import re
from pathlib import Path
from zoneinfo import ZoneInfo


REPO_ROOT = Path(__file__).resolve().parents[1]
INDEX = REPO_ROOT / "index.html"
REPORT_DIR = REPO_ROOT / "reports"
PT = ZoneInfo("America/Los_Angeles")

BAD_INCLUDED_MARKERS = [
    "Could not verify",
    "live Jan",
    "live Feb",
    "live Mar",
    "live Apr",
    "live May",
    "live Jun",
    "live Jul",
    "live Aug",
    "live Sep",
    "live Oct",
    "live Nov",
    "live Dec",
]

BAD_LOCATION_MARKERS = [
    "san francisco, ca · hybrid",
    "sf hybrid",
    "san francisco hybrid",
    "bay area · hybrid",
    "san francisco, ca hybrid",
]


def latest_report() -> Path | None:
    reports = sorted(REPORT_DIR.glob("*.md"))
    return reports[-1] if reports else None


def failed_included_urls(report_text: str) -> set[str]:
    urls: set[str] = set()
    for line in report_text.splitlines():
        if "Full-Time Roles link failed:" not in line and "Fractional & Advisory link failed:" not in line:
            continue
        match = re.search(r"https?://\S+", line)
        if match:
            urls.add(match.group(0).rstrip(").,"))
    return urls


def remove_bad_articles(html: str, bad_urls: set[str]) -> tuple[str, int]:
    included_end = html.find('id="tab-content-all"')
    if included_end == -1:
        included_end = len(html)

    included = html[:included_end]
    rest = html[included_end:]
    removed = 0
    output: list[str] = []
    cursor = 0

    for match in re.finditer(r"<article[\s\S]*?</article>", included):
        article = match.group(0)
        lower = article.lower()
        is_bad = any(marker in article for marker in BAD_INCLUDED_MARKERS)
        is_bad = is_bad or any(marker in lower for marker in BAD_LOCATION_MARKERS)
        is_bad = is_bad or any(url in article for url in bad_urls)

        output.append(included[cursor:match.start()])
        if is_bad:
            removed += 1
        else:
            output.append(article)
        cursor = match.end()

    output.append(included[cursor:])
    return "".join(output) + rest, removed


def normalize_static_contract(html: str) -> str:
    html = html.replace("switchTab('sources')", "switchTab('all')")
    html = html.replace('id="tab-sources"', 'id="tab-all"')
    html = html.replace('id="tab-content-sources"', 'id="tab-content-all"')
    html = html.replace("Generated by Claude Code", "Generated by Codex/GitHub Actions")
    return html


def fix_visible_day_string(html: str) -> str:
    today = dt.datetime.now(PT).date()
    today_iso = today.isoformat()
    if today_iso not in html:
        return html
    expected = today.strftime("%A, %b %-d %Y")
    pattern = re.compile(
        r"\b(Monday|Tuesday|Wednesday|Thursday|Friday|Saturday|Sunday),\s+"
        r"(Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)\s+"
        r"\d{1,2}\s+\d{4}\b"
    )
    return pattern.sub(expected, html, count=1)


def main() -> int:
    if not INDEX.exists():
        raise FileNotFoundError(INDEX)

    original = INDEX.read_text()
    html = normalize_static_contract(original)
    html = fix_visible_day_string(html)

    report = latest_report()
    bad_urls = failed_included_urls(report.read_text()) if report else set()
    html, removed = remove_bad_articles(html, bad_urls)

    if html == original:
        print("No safe fixes needed")
        return 0

    INDEX.write_text(html)
    print(f"Safe fixes applied; removed_articles={removed}; bad_urls={len(bad_urls)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
