#!/usr/bin/env python3
"""Validate local static HTML contracts that should not depend on the live site."""

from __future__ import annotations

import sys
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]
REQUIRED = [
    'id="tab-content-fulltime"',
    'id="tab-content-fractional"',
    'id="tab-content-all"',
]
REQUIRED_INDEX_LINKS = [
    'href="/job-alerts/criteria.html"',
    "issues/new?template=bug_report.md",
    "actions/workflows/daily-generate.yml",
]
REQUIRED_PAGE_MARKERS = {
    "criteria.html": [
        'id="criteria-editor"',
        "Submit Update",
        "criteria_update.md",
        'data-criteria-list="primary_domain_keywords"',
        'data-criteria-list="excluded_title_keywords"',
        'id="minimum-score"',
    ],
}
FORBIDDEN = [
    'id="tab-content-sources"',
    'id="tab-sources"',
    "switchTab('sources')",
    "Generated by Claude Code",
    'href="/job-alerts/settings.html"',
    'id="settings-page"',
    'id="criteria-json"',
]
PLACEHOLDERS = [
    "TODAY_DATE",
    "GENERATION_TIME",
    "FULLTIME_COUNT",
    "SUMMARY_NOTE",
    "APPLY_URL",
]


def validate(path: Path, *, allow_placeholders: bool) -> list[str]:
    html = path.read_text()
    failures: list[str] = []
    for token in REQUIRED:
        if token not in html:
            failures.append(f"{path.name}: missing {token}")
    for token in FORBIDDEN:
        if token in html:
            failures.append(f"{path.name}: forbidden legacy token {token}")
    if path.name == "index.html":
        for token in REQUIRED_INDEX_LINKS:
            if token not in html:
                failures.append(f"{path.name}: missing {token}")
        if 'id="tab-content-criteria"' in html or "switchTab('criteria')" in html:
            failures.append(f"{path.name}: criteria should be a separate page, not a tab")
        if 'target="_blank" class="inline-flex items-center justify-center rounded bg-white text-slate-900 px-3 py-2 text-xs font-semibold hover:bg-slate-100">Feedback</a>' in html:
            failures.append(f"{path.name}: feedback should live inside the hamburger menu")
    if not allow_placeholders:
        for token in PLACEHOLDERS:
            if token in html:
                failures.append(f"{path.name}: unreplaced placeholder {token}")
    return failures


def main() -> int:
    failures: list[str] = []
    failures.extend(validate(REPO_ROOT / "template.html", allow_placeholders=True))
    failures.extend(validate(REPO_ROOT / "index.html", allow_placeholders=False))
    for name, markers in REQUIRED_PAGE_MARKERS.items():
        path = REPO_ROOT / name
        if not path.exists():
            failures.append(f"{name}: missing generated page")
            continue
        html = path.read_text()
        for token in markers:
            if token not in html:
                failures.append(f"{name}: missing {token}")
        for token in FORBIDDEN:
            if token in html:
                failures.append(f"{name}: forbidden legacy token {token}")
    if (REPO_ROOT / "settings.html").exists():
        failures.append("settings.html: dedicated settings page should not exist")
    if failures:
        print("\n".join(failures), file=sys.stderr)
        return 1
    print("Static contract validation passed")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
